export interface Agent {
  id: string
  name: string
  category: string
  description: string
  tags: string[]
  color: string
  icon: string
  whatsappUrl?: string
}

export const agents: Agent[] = [
  {
    id: "tubechat",
    name: "TubeChat",
    category: "Entretenimiento",
    description: "Tu asistente personal de WhatsApp para búsquedas instantáneas y respuestas rápidas de voz",
    tags: ["asistente", "búsqueda", "voz"],
    color: "#3B82F6",
    icon: "TC",
  },
  {
    id: "eva",
    name: "EVA",
    category: "Asistente Virtual",
    description: "Transcribe y resume tus audios de WhatsApp",
    tags: ["transcripción", "audio", "resumen"],
    color: "#8B5CF6",
    icon: "E",
  },
  {
    id: "privacycv",
    name: "PrivacyCV",
    category: "Recursos Humanos",
    description: "Revisa tu CV con IA basada en un experto reclutador",
    tags: ["reclutamiento", "cv", "recursos humanos"],
    color: "#F59E0B",
    icon: "P",
  },
  {
    id: "bot-nutribot",
    name: "Bot Nutribot",
    category: "Salud y Bienestar",
    description: "Sugerencias de comida con IA registro de entrenamientos y consejos para WhatsApp",
    tags: ["nutrición", "salud", "ejercicio"],
    color: "#EF4444",
    icon: "N",
  },
  {
    id: "wasap-finance",
    name: "Wasap Finance",
    category: "Finanzas",
    description: "Registra tus gastos desde WhatsApp",
    tags: ["finanzas", "gastos", "contabilidad"],
    color: "#10B981",
    icon: "W",
  },
  {
    id: "papita-crop-doctor",
    name: "Papita Crop Doctor",
    category: "Agricultura",
    description: "Convierte tu WhatsApp en un poderoso doctor de cultivos",
    tags: ["agricultura", "cultivos", "diagnóstico"],
    color: "#F59E0B",
    icon: "P",
  },
  {
    id: "transcribeme",
    name: "TranscribeMe",
    category: "Productividad",
    description: "Convierte las notas de voz de WhatsApp en texto",
    tags: ["transcripción", "voz", "texto"],
    color: "#F59E0B",
    icon: "T",
  },
  {
    id: "bori",
    name: "Bori",
    category: "Entretenimiento",
    description: "Tutor de matemáticas con IA transformando la educación para los que más lo necesitan",
    tags: ["educación", "matemáticas", "tutoría"],
    color: "#8B5CF6",
    icon: "B",
  },
  {
    id: "recordai",
    name: "RecordAI",
    category: "Productividad",
    description: "Un grupo en WhatsApp para configurar recordatorios y eventos",
    tags: ["recordatorios", "eventos", "productividad"],
    color: "#F59E0B",
    icon: "R",
  },
  {
    id: "shortify-ai",
    name: "Shortify AI",
    category: "Productividad",
    description: "Crea links de 5 minutos con IA directamente en WhatsApp",
    tags: ["links", "resumen", "IA"],
    color: "#F59E0B",
    icon: "S",
  },
  {
    id: "kaptron",
    name: "Kaptron",
    category: "Educación",
    description: "Nueva escuelas en audio largo de nueva generación",
    tags: ["educación", "audio", "aprendizaje"],
    color: "#3B82F6",
    icon: "K",
  },
  {
    id: "easyscribe",
    name: "EasyScribe",
    category: "Productividad",
    description: "Convierte tus mensajes de voz de WhatsApp en texto",
    tags: ["transcripción", "voz", "texto"],
    color: "#10B981",
    icon: "E",
  },
  {
    id: "writerry",
    name: "Writerry",
    category: "Escritura",
    description:
      "Plataforma Los mensajes de WhatsApp en múltiples modalidades con texto, imágenes y audios optimizados",
    tags: ["escritura", "contenido", "multimedia"],
    color: "#3B82F6",
    icon: "W",
  },
  {
    id: "fotolab-ai",
    name: "FotoLab AI",
    category: "Fotografía",
    description: "Crea fotos realistas con IA en WhatsApp",
    tags: ["fotografía", "IA", "imágenes"],
    color: "#3B82F6",
    icon: "F",
  },
  {
    id: "secret-app",
    name: "Secret App",
    category: "Entretenimiento",
    description: "Envía secretos a grupos de WhatsApp de forma anónima IA",
    tags: ["anónimo", "secretos", "grupos"],
    color: "#10B981",
    icon: "S",
  },
  {
    id: "nautalk",
    name: "NauTalk",
    category: "Comunicación",
    description: "Primera plataforma de traducción que te permite comunicarte con personas de todo el mundo",
    tags: ["traducción", "comunicación", "idiomas"],
    color: "#3B82F6",
    icon: "N",
  },
  {
    id: "lexa",
    name: "Lexa",
    category: "Legal",
    description: "Soy Lexa, asistente virtual Fiscal de Mendoza Poder Fiscal de Mendoza",
    tags: ["legal", "asistente", "fiscal"],
    color: "#EF4444",
    icon: "L",
  },
  {
    id: "yevmendel",
    name: "YevMendel",
    category: "E-commerce",
    description: "Traduce las ventas de tu ecommerce con un vendedor virtual que responde por ti 24/7",
    tags: ["ventas", "ecommerce", "automatización"],
    color: "#F59E0B",
    icon: "Y",
  },
  {
    id: "ella",
    name: "Ella",
    category: "Salud Mental",
    description:
      "Configura tus compromisos diarios saludables y personales por WhatsApp para que ella te los recuerde cada día",
    tags: ["bienestar", "recordatorios", "salud mental"],
    color: "#8B5CF6",
    icon: "E",
  },
  {
    id: "whabot",
    name: "Whabot",
    category: "Automatización",
    description: "Pon en tus chat piezas, recetas básicas y un recetario de platos típicos americanos",
    tags: ["recetas", "cocina", "automatización"],
    color: "#3B82F6",
    icon: "W",
  },
  {
    id: "sory",
    name: "Sory",
    category: "E-commerce",
    description: "Agente IA entrenado en temas de creación y crecimiento de productos digitales Producto & Servicio",
    tags: ["productos digitales", "crecimiento", "consultoría"],
    color: "#EF4444",
    icon: "S",
  },
  {
    id: "vita",
    name: "Vita",
    category: "Salud",
    description: "Conocemos la necesidad del paciente por el Cuidado de la Salud",
    tags: ["salud", "cuidado", "pacientes"],
    color: "#EF4444",
    icon: "V",
  },
  {
    id: "gesti-pro",
    name: "Gesti Pro",
    category: "Gestión",
    description: "Mantenga your finanzas, el easy de ventas y mensajes",
    tags: ["finanzas", "ventas", "gestión"],
    color: "#10B981",
    icon: "G",
  },
  {
    id: "asistente-pka",
    name: "Asistente PKA",
    category: "Asistente Personal",
    description: "Asistente personal para cada uno de tus conversaciones",
    tags: ["asistente", "personal", "conversaciones"],
    color: "#8B5CF6",
    icon: "A",
  },
  {
    id: "instaflex",
    name: "InstaFlex",
    category: "Fotografía",
    description: "AI para fotografía con IA - Sin Estudios Sin Fotógrafo",
    tags: ["fotografía", "IA", "automatización"],
    color: "#F59E0B",
    icon: "I",
  },
  {
    id: "awa",
    name: "AWA",
    category: "Automatización",
    description: "Automatiza automática por WhatsApp con IA",
    tags: ["automatización", "IA", "WhatsApp"],
    color: "#3B82F6",
    icon: "A",
  },
  {
    id: "genii",
    name: "Genii",
    category: "Productividad",
    description: "Gestión de medicamentos en 30 min",
    tags: ["medicamentos", "gestión", "salud"],
    color: "#EF4444",
    icon: "G",
  },
  {
    id: "domus-ai",
    name: "Domus AI - Asistente Personal",
    category: "Asistente Personal",
    description: "Automatizamos la gestión inmobiliaria con AI agents",
    tags: ["inmobiliaria", "gestión", "automatización"],
    color: "#10B981",
    icon: "D",
  },
  {
    id: "zaela",
    name: "Zaela",
    category: "Inteligencia Artificial",
    description: "Tu asistente de Inteligencia Artificial",
    tags: ["asistente", "IA", "inteligencia artificial"],
    color: "#10B981",
    icon: "Z",
  },
  {
    id: "cala-ai",
    name: "Cala AI",
    category: "Automatización",
    description: "Tu asistente especializado de Compliance para ayudarte a navegar en base a tus grupos",
    tags: ["compliance", "asistente", "navegación"],
    color: "#EF4444",
    icon: "C",
  },
  {
    id: "simple",
    name: "Simple",
    category: "Productividad",
    description: "Crea visualizaciones PDF en segundos y más, las herramientas en una sola negocio de servicios",
    tags: ["PDF", "visualizaciones", "herramientas"],
    color: "#8B5CF6",
    icon: "S",
  },
  {
    id: "medcamp-ia",
    name: "MedCamp IA",
    category: "Salud",
    description: "Transforma tu atención médica con inteligencia artificial y telemedicina",
    tags: ["salud", "telemedicina", "IA"],
    color: "#F59E0B",
    icon: "M",
  },
  {
    id: "alejo-jobs",
    name: "Alejo Jobs",
    category: "Empleo",
    description: "Asistente virtual para acelerar procesos de búsqueda laboral",
    tags: ["empleo", "búsqueda laboral", "asistente"],
    color: "#F59E0B",
    icon: "A",
  },
  {
    id: "dinta",
    name: "Dinta",
    category: "Inteligencia Artificial",
    description: "Tu Inteligencia Artificial que te ayuda a optimizar procesos",
    tags: ["IA", "optimización", "procesos"],
    color: "#10B981",
    icon: "D",
  },
  {
    id: "solucre",
    name: "Solucre",
    category: "Soluciones",
    description: "Venta de energías fiscales y líneas",
    tags: ["energía", "ventas", "soluciones"],
    color: "#3B82F6",
    icon: "S",
  },
  {
    id: "la-canasta",
    name: "La Canasta",
    category: "E-commerce",
    description: "Venta de energías fiscales y líneas",
    tags: ["ventas", "energía", "comercio"],
    color: "#10B981",
    icon: "L",
  },
  {
    id: "chatgpt-whatsapp",
    name: "ChatGPT WhatsApp",
    category: "Inteligencia Artificial",
    description: "Accede a ChatGPT directamente desde WhatsApp",
    tags: ["ChatGPT", "IA", "conversación"],
    color: "#10B981",
    icon: "C",
  },
  {
    id: "ai-translator",
    name: "AI Translator",
    category: "Comunicación",
    description: "Traductor inteligente para WhatsApp con múltiples idiomas",
    tags: ["traducción", "idiomas", "comunicación"],
    color: "#3B82F6",
    icon: "T",
  },
  {
    id: "voice-assistant",
    name: "Voice Assistant",
    category: "Asistente Virtual",
    description: "Asistente de voz inteligente para WhatsApp",
    tags: ["voz", "asistente", "audio"],
    color: "#8B5CF6",
    icon: "V",
  },
  {
    id: "smart-scheduler",
    name: "Smart Scheduler",
    category: "Productividad",
    description: "Programa y gestiona tus citas desde WhatsApp",
    tags: ["citas", "programación", "calendario"],
    color: "#F59E0B",
    icon: "S",
  },
  {
    id: "expense-tracker",
    name: "Expense Tracker",
    category: "Finanzas",
    description: "Rastrea y categoriza tus gastos automáticamente",
    tags: ["gastos", "finanzas", "seguimiento"],
    color: "#EF4444",
    icon: "E",
  },
  {
    id: "fitness-coach",
    name: "Fitness Coach",
    category: "Salud y Bienestar",
    description: "Tu entrenador personal de fitness en WhatsApp",
    tags: ["fitness", "ejercicio", "salud"],
    color: "#10B981",
    icon: "F",
  },
  {
    id: "recipe-bot",
    name: "Recipe Bot",
    category: "Cocina",
    description: "Encuentra recetas personalizadas según tus ingredientes",
    tags: ["recetas", "cocina", "ingredientes"],
    color: "#F59E0B",
    icon: "R",
  },
  {
    id: "study-buddy",
    name: "Study Buddy",
    category: "Educación",
    description: "Asistente de estudio con IA para estudiantes",
    tags: ["estudio", "educación", "aprendizaje"],
    color: "#8B5CF6",
    icon: "S",
  },
  {
    id: "weather-bot",
    name: "Weather Bot",
    category: "Información",
    description: "Pronóstico del tiempo personalizado para tu ubicación",
    tags: ["clima", "pronóstico", "ubicación"],
    color: "#3B82F6",
    icon: "W",
  },
  {
    id: "news-digest",
    name: "News Digest",
    category: "Información",
    description: "Resumen diario de noticias personalizadas",
    tags: ["noticias", "resumen", "información"],
    color: "#EF4444",
    icon: "N",
  },
  {
    id: "travel-planner",
    name: "Travel Planner",
    category: "Viajes",
    description: "Planifica tus viajes con recomendaciones inteligentes",
    tags: ["viajes", "planificación", "turismo"],
    color: "#10B981",
    icon: "T",
  },
  {
    id: "meditation-guide",
    name: "Meditation Guide",
    category: "Bienestar",
    description: "Guía de meditación y mindfulness personalizada",
    tags: ["meditación", "mindfulness", "bienestar"],
    color: "#8B5CF6",
    icon: "M",
  },
  {
    id: "language-tutor",
    name: "Language Tutor",
    category: "Educación",
    description: "Aprende idiomas con conversaciones naturales",
    tags: ["idiomas", "aprendizaje", "conversación"],
    color: "#F59E0B",
    icon: "L",
  },
  {
    id: "crypto-tracker",
    name: "Crypto Tracker",
    category: "Finanzas",
    description: "Seguimiento de criptomonedas y alertas de precio",
    tags: ["criptomonedas", "precios", "inversiones"],
    color: "#3B82F6",
    icon: "C",
  },
  {
    id: "habit-tracker",
    name: "Habit Tracker",
    category: "Productividad",
    description: "Construye y mantén hábitos saludables",
    tags: ["hábitos", "seguimiento", "productividad"],
    color: "#10B981",
    icon: "H",
  },
  {
    id: "job-finder",
    name: "Job Finder",
    category: "Empleo",
    description: "Encuentra oportunidades laborales personalizadas",
    tags: ["empleo", "trabajo", "oportunidades"],
    color: "#EF4444",
    icon: "J",
  },
  {
    id: "plant-care",
    name: "Plant Care",
    category: "Jardinería",
    description: "Cuidado inteligente de plantas y jardines",
    tags: ["plantas", "jardinería", "cuidado"],
    color: "#10B981",
    icon: "P",
  },
  {
    id: "mood-tracker",
    name: "Mood Tracker",
    category: "Salud Mental",
    description: "Registra y analiza tu estado de ánimo diario",
    tags: ["estado de ánimo", "salud mental", "seguimiento"],
    color: "#8B5CF6",
    icon: "M",
  },
  {
    id: "book-recommender",
    name: "Book Recommender",
    category: "Entretenimiento",
    description: "Recomendaciones personalizadas de libros",
    tags: ["libros", "lectura", "recomendaciones"],
    color: "#F59E0B",
    icon: "B",
  },
  {
    id: "password-manager",
    name: "Password Manager",
    category: "Seguridad",
    description: "Gestiona tus contraseñas de forma segura",
    tags: ["contraseñas", "seguridad", "gestión"],
    color: "#EF4444",
    icon: "P",
  },
  {
    id: "dream-journal",
    name: "Dream Journal",
    category: "Bienestar",
    description: "Registra y analiza tus sueños con IA",
    tags: ["sueños", "análisis", "bienestar"],
    color: "#8B5CF6",
    icon: "D",
  },
]
